# Generated by Django 3.2.6 on 2022-09-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=50, verbose_name='Site Name')),
                ('url', models.TextField(verbose_name='Site URL')),
                ('img', models.TextField(verbose_name='Site Img')),
            ],
        ),
    ]
