# Generated by Django 4.1.1 on 2022-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favsite',
            name='img',
            field=models.TextField(blank=True, verbose_name='Site Img'),
        ),
    ]
