# Generated by Django 4.1.1 on 2022-09-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_favsite_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='favsite',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Site Priority'),
        ),
        migrations.AddField(
            model_name='newssite',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Site Priority'),
        ),
    ]
